name: Publish

on:
  push:
    branches:
      - main

permissions:
  id-token: write

jobs:
  uv-example:
    name: python
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v4
        with:
          enable-cache: true

      - name: Prepare Dependencies
        run: uv sync

      - name: Build Project
        run: uv build

      - name: Publish
        run: uv publish
